-- db schema


CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	oauth_id VARCHAR(255) DEFAULT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	picture VARCHAR(255) DEFAULT NULL,
	oauth VARCHAR(255) DEFAULT "google",
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
  
  
CREATE TABLE users_session (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	login_token VARCHAR(255) NOT NULL,
	ip_addr VARCHAR(255) NOT NULL,
	superseded TINYINT(1) DEFAULT 0,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
  